<?php

$post_img = $this->url->get('files/' . $post[0]->file);
$post_desc = $post[0]->description;
$post_id = $post[0]->id;

$tokenName = $this->security->getTokenKey();
$tokenValue = $this->security->getToken();


echo "  

    <div class='card mb-3'>
        <img class='card-img-top' style='height:300px;' src='$post_img' alt='Card image cap'>
        <div class='card-body'>
            <h5 class='card-title'>$post_desc</h5>
            <p class='card-text'></p>
            <form action='/order/index/create' method='post'>

                <textarea style='widht : 100%;' cols='100%' name='order_description' placeholder='description'></textarea>
                
                <input type='hidden' name='post_id'
                    value='$post_id'/>

                <input type='hidden' name='$tokenName'
                    value='$tokenValue'/>
                    <br>
                <button class='btn btn-primary' type='submit'>order</button>

            </form>
        </div>
    </div>
    
    ";

?>


<form action="/comment/index/create" method="post">

    <textarea name="comment" id="comment" cols="50" rows="2" placeholder='Leave a comment'></textarea>

    <input type='hidden' name='<?php echo $this->security->getTokenKey() ?>'
        value='<?php echo $this->security->getToken() ?>'/>

    <input type='hidden' name='post_id'
                value="<?php echo $post[0]->id; ?>" />


    <input class='btn btn-info' type="submit" value="comment">

</form>

<div class="card" style="width: 18rem;">
  <ul class="list-group list-group-flush">
    <?php

        foreach ($comments as $comment) {
            echo "
                <li class='list-group-item'>$comment->comment</li>
            ";
        }

    ?>
  </ul>
</div>

