<div class="page-header">
    <h1>Post !</h1>
</div>


<?php

foreach ($posts as $post) {

    $tokenName = $this->security->getTokenKey();
    $tokenValue = $this->security->getToken();
    $post_desc = $post->description();
    $post_rate = $post->averageRating();

    echo "$post_desc <br> $post_rate <br>
    
    <form action='/post/index/rating' method='post'>

        <input type='radio' id='star1' name='rating' value=1>
        <label for='star1'>1 Star</label><br>
        <input type='radio' id='star2' name='rating' value=2>
        <label for='star2'>2 Star</label><br>
        <input type='radio' id='star3' name='rating' value=3>
        <label for='star3'>3 Star</label><br>
        <input type='radio' id='star4' name='rating' value=4>
        <label for='star4'>4 Star</label><br>
        <input type='radio' id='star5' name='rating' value=5>
        <label for='star5'>5 Star</label><br>

        <input type='hidden' name='$tokenName'
        value='$tokenValue'/>

        <button type='submit'>submit</button>
    </form> 
    
    ";
}

?>