<div class="page-header">
    <h1>Users page</h1>
</div>

<form class="input_container" method="POST" action="/user/index/register">

    <?php echo $regForm->render('nickname'); ?>
    <br/>

    <?php echo $regForm->render('email'); ?>
    <br/>

    <?php echo $regForm->render('password'); ?>
    <br/>

    <input type='hidden' name='<?php echo $this->security->getTokenKey() ?>'
        value='<?php echo $this->security->getToken() ?>'/>

    <input type="submit" value="SignUp">
</form>

<form class="input_container" method="POST" action="/user/index/login">

    <?php echo $loginForm->render('email'); ?>
    <br/>
    <?php echo $loginForm->render('password'); ?>
    <br/>

    <input type='hidden' name='<?php echo $this->security->getTokenKey() ?>'
        value='<?php echo $this->security->getToken() ?>'/>

    <input type="submit" value="Login">
</form>