<div class="page-header">
    <h1>Congratulations!</h1>
</div>

<a href="/user/index/logout">Logout</a>

<form action="/post/index/create" method="post">

    <input type="text" name="description" placeholder="description">
    <input type="text" name="file" placeholder="file">

    <input type='hidden' name='<?php echo $this->security->getTokenKey() ?>'
        value='<?php echo $this->security->getToken() ?>'/>

    <button type="submit">submit</button>

</form>
