<div class="page-header">
    <h1>Post job</h1>
</div>

<form action="/post/index/create" method="post" enctype="multipart/form-data">

    <input type="text" name="description" placeholder="description">
    <input type="file" name="file" placeholder="file">

    <!-- <input type='hidden' name='user_id' value=''/> -->

    <input type='hidden' name='<?php echo $this->security->getTokenKey() ?>'
        value='<?php echo $this->security->getToken() ?>'/>

    <button type="submit">submit</button>

</form>

<?php

    foreach ($posts as $post) {
        echo "$post->description <br>";
    }

?>
